### ISSUE TITLE
linter should spot "missing definitions".  

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#19]
Sometimes the VoLL-KI UI cannot find definitions, as @Jazzpirate points out in https://github.com/slatex/sTeX/issues/362. So the linter should be able to predict this and give a warning so these can be fixed.

**Comment by kohlhase** [comment]
Just flagging `{sdefinition}` environments without a `\defi*` would go a long way. 

Better still, flagging all `\symdef` and `\symdecl*` that do not have a `\defi*` in the module would be a great quality assurance feature.

**Comment by Jazzpirate** [comment]
this is tricky, since, since the \symdef and the \defi* occur in entirely different places and potentially even in different documents. Not something to be "quickly hacked", unfortunately :-/

**Comment by Jazzpirate** [comment]
Done

**Comment by kohlhase** [comment]
This is wonderful, but it still misses some "documentation". For instance `\Definame`. 
<img width="364" alt="Screenshot 2022-09-29 at 10 50 52" src="https://user-images.githubusercontent.com/4037538/192986884-4d96f1ee-3ed6-4b90-9f4c-e926a8c44e3a.png">

**Comment by Jazzpirate** [comment]
True, I forgot the "Definame"-case (pushed) - anything else it's missing?

**Comment by kohlhase** [comment]
The Definame problem is not (fully?) fixed yet with that push. The screenshot shows an instance. This might be an interaction between `\Definame` and `ambiguous symbols`?

**Comment by kohlhase** [comment]
apart from this, these warnings are a very useful feature, most of the (legitimate) ones seem to be due to symbols that have a `\symdef` without a `name=` and corresponding `\symdecl*` and thus easily fixed.

**Comment by kohlhase** [comment]
and t

> The Definame problem is not (fully?) fixed yet with that push. The screenshot shows an instance. This might be an interaction between `\Definame` and `ambiguous symbols`?

and here the screenshot: 
<img width="708" alt="Screenshot 2022-09-29 at 12 11 33" src="https://user-images.githubusercontent.com/4037538/193005456-c0a38ea4-e102-4cd7-8336-edd910d87851.png">

**Comment by Jazzpirate** [comment]
Oh, but given ambiguity, this is correct. The Definame is for "poplanning?partial-order-planing", not for the above "poplan-process?partial-order-planning". In other words: the latter really *is* undocumented :)

**Comment by kohlhase** [comment]
Ah, you are right, thanks. Then that has to be fixed a different way than I thought.

**Comment by kohlhase** [comment]
But there is a related issue. There are some `\symdef`s that I do not WANT to define or document. 

Is it possible to just add a key `nodef` to `\symdef` that can be used to express this?

**Comment by kohlhase** [comment]
For clarification these symbols are mostly in examples, and are the semantic macros used in representations there. 
An example of this is `MiKoMH/AI/source/ planning/slides/strips-blocksworld.en.tex` where I am not quite sure how to best flexiformalize this.

**Comment by Jazzpirate** [comment]
> There are some `\symdef`s that I do not WANT to define or document.

I disagree. There are no symbols you do not want to be documented ;) Think of the documentation as "what students should see if they're confused by what this means".

The solution for strips-blocksworld could/would be to just add a [for={} to the already present sdefinition and list all predicates there. Or even better: wrap the sexample below in a {sparagraph}[type=symdoc,for={}] and put the predicates in there. Then that's what students get to see if they hover over the symbols.

> Is it possible to just add a key `nodef` to `\symdef` that can be used to express this?

I don't think it a good idea to introduce stex-package functionality (such as keys in macros) for mere IDE linting aspects in general...

**Comment by kohlhase** [comment]
Ah, thanks. You are right.
