### ISSUE TITLE
linter behaves differently in en and de

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#20]
in `smglom/algebra/source/mod/inverse.en.tex` I get no warning in , but in `inverse.de.tex` I get the following one:
<img width="966" alt="Screenshot 2022-09-29 at 13 06 23" src="https://user-images.githubusercontent.com/4037538/193015925-9d92947c-a3fc-43fb-a528-d7e48449a5a4.png">

And do not tell me that this is intentional, ...

**Comment by Jazzpirate** [comment]
Are the modules up to date on gl.mathhub.info?

**Comment by kohlhase** [comment]
now they are.

**Comment by Jazzpirate** [comment]
ah, nevermind: Notice how there's a `\symdef{leftinv}` in inverse.de.tex that shouldn't be there - the ambiguity is real.

One *could* think about throwing warnings for \symdefs et al occuring in language modules, but I'm not sure we want to forbid them entirely...

**Comment by kohlhase** [comment]
Ah, good that you have your eyes open, I apparently did not.
