### ISSUE TITLE
linter seems to disregard [name= in mathstructure

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#21]
In `smglom/linear-algebra/source/mode/vector-space.en.tex` we have 
```
\begin{mathstructure}{vecspace}[name=vector-space]
```
but in `linear-map.en.tex` there we `vector-space` as a module name does not seem to work: 
<img width="544" alt="Screenshot 2022-09-29 at 16 48 59" src="https://user-images.githubusercontent.com/4037538/193064435-1f19ab5a-0152-497d-b828-003df583e003.png">
in the `\varinstantiate` and the `\usemodule`. Note that the `vecspace` in line 10 does work. This occurs in many cases.

**Comment by Jazzpirate** [comment]
ist this a complaint from the linter or does it not compile either (i.e. do I only need to fix the linter or sTeX itself as well)? Could you quickly check?

**Comment by kohlhase** [comment]
```
./linear-map.en.tex:11: Package stex Error: No structure vecspace found!

Type <return> to continue.
 ...                                              
                                                  
```
so the linter needs `vecspace` and pdflatex `vector-space`

**Comment by Jazzpirate** [comment]
ok, then I will have to check what the actual *semantics* of "name=" for mathstructures is even intended to be...

**Comment by Jazzpirate** [comment]
fixed and pushed sTeX and MMT

**Comment by Jazzpirate** [comment]
this seems to be solved now
