### ISSUE TITLE
linter seems to stumble over URLs. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#22]
It signals the error that various environments do not close. 

e.g. in `MiKoProblems/AI/source/prolog/mod/csp-map-coloring.en.tex` or `MiKoProblems/AI/source/prolog/mod/tree-search.en.tex`

**Comment by Jazzpirate** [comment]
Indeed, the problem was the `%`-characters in URLs. Fixed (in the upcoming MMT commit)
