### ISSUE TITLE
error in linter error message?

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#23]
I get the following the `true` at the end seems wrong. 
<img width="582" alt="Screenshot 2022-09-30 at 08 33 16" src="https://user-images.githubusercontent.com/4037538/193205738-275f4b98-ae42-479d-8ede-86f1f782bee7.png">

**Comment by Jazzpirate** [comment]
Indeed, that was a leftover from printline-debugging :D Removed (upcoming MMT-commit)
