### ISSUE TITLE
linter issues warning for the first and last for= entries

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#25]
e.g. in `MiKoMH/GenCS/source/logic/slides/whatislogic.en.tex`: 

<img width="702" alt="Screenshot 2022-10-03 at 13 42 05" src="https://user-images.githubusercontent.com/4037538/193568888-26f4606b-4555-458d-adc1-fefb9f5786a7.png">

**Comment by Jazzpirate** [comment]
Fixed (pushed MMT)
