### ISSUE TITLE
linter: wrong "not documented error" 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#34]
in `smglom/voll-ki/source/mod/CFS.en.tex`: 
<img width="788" alt="Screenshot 2023-03-25 at 10 04 22" src="https://user-images.githubusercontent.com/4037538/227708007-ff4f83d2-b385-4608-9285-8c095883986e.png">

**Comment by Jazzpirate** [comment]
Looks correct to me? If the sdefinition below is to serve as a documentation, then it either has to list CFS in `for=`, or, more likely, you want to use `\definiendum`/`\definame` instead of `\symref`/`\symname` ;)

**Comment by kohlhase** [comment]
Dang, you are right. We only see what we expect to see. Sorry
