### ISSUE TITLE
linter does not take \definame in \inlinedef into account. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#37]
in `MiKoMH/AI/source/rational-agents/slides/peas.en.tex` we have a `\definame{PEAS}` in an `\inlinedef` that is not picked up by the linter, which signals `PEAS` to be undefined. 
<img width="743" alt="Screenshot 2023-10-25 at 21 35 12" src="https://github.com/slatex/sTeX-IDE/assets/4037538/15bf1eea-29e2-4554-82ce-23c26db0a0d6">

**Comment by Jazzpirate** [comment]
fixed (pushed MMT on devel)

**Comment by kohlhase** [comment]
thanks a lot
