### ISSUE TITLE
linter does not pick up \definame[post=s]{foo}

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#38]
In `smglom/csp/source/mod/csp.en.tex` I have  `\definame[post=s]{constraint}` and the `\symdecl*{constraint}` is still marked as undocumented.

**Comment by Jazzpirate** [comment]
The problem here is an `ambiguous symbol reference`: You have `csp?constraint` and in the `{mathstructure}{csp}` another `\symdef{constr}[name=constraint]`. The `\definame` picks up on the latter, leaving the former undefined

**Comment by kohlhase** [comment]
yes, you are right I realized that along the way, and have started fixing these things. (there are about 4500 to go)
