### ISSUE TITLE
vardef linter problem?

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#6]
On `/MathHub/smglom/topology/source/fundamental-group.en.tex` I get a linter error that I cannot explain. 
<img width="910" alt="Screenshot 2022-09-12 at 08 03 59" src="https://user-images.githubusercontent.com/4037538/189584420-cf8341ea-ab57-4f5b-a560-ab212b4ae6af.png">

**Comment by Jazzpirate** [comment]
Fixed with MMT commit (missing support for \text escaping from math mode)
