### ISSUE TITLE
problems with finding tree?root

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#7]
There still seems to be a problem with the linter, in `MathHub/MiKoMH/GenCS/source/atp0/mod/tableaux-formal.en.tex` two instances of `\symname{tree?tree}` give a `could not find symbol` error, whereas other instances are OK. And the `tree` module is imported (via `branch`).

**Comment by kohlhase** [comment]
There are quite a lot of errors that are similar (all with tree)  all over the corpus.

**Comment by Jazzpirate** [comment]
That's because "tree" is a nested module - it's actually called `tree/tree-structure`. If you need to disambiguate it, you need to do `\symname{tree/tree-structure?tree}`

**Comment by kohlhase** [comment]
OK, I understand. But the linter does not seem to offer the disambiguation to me when I remove the `tree?`

**Comment by Jazzpirate** [comment]
...It did for me (I already did that in several places in smglom/graphs, and indeed the quickest way was to just delete the `tree?` prefix and immediately get a quick fix)...
do you have a concrete example?

**Comment by kohlhase** [comment]
I have restarted vscode and I now have problems with `MathHub/MiKoMH/IWGS/source/digdocs/mod/lxml-elements.en.tex`
There the linter does not find `tree/tree-structure` components even thougt the module is imported. 
![Uploading Screenshot 2022-09-12 at 08.53.51.png…]()

**Comment by Jazzpirate** [comment]
there are some other problems with {usestructure} and imports/extstructure as well. Currently fixing, then will check again

**Comment by Jazzpirate** [comment]
Fixed some things, but lxml-elements (as on gl.mathhub.info) does not import tree/tree-structure anywhere...?
If I wrap the first frame in a {usestructure}{tree}, everything is linted correctly (now), pushed MiKoMH/IWGS as well to add the usestructure.
