### ISSUE TITLE
linter problem? 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-IDE#9]
In `MiKoMH/GenCS/machines/mod/halting-problem.en.tex` I have an ambiguity problem deteced by the linter. 
<img width="1133" alt="Screenshot 2022-09-20 at 14 11 38" src="https://user-images.githubusercontent.com/4037538/191231574-e503c941-2803-42a8-b1b1-26725a9216d4.png">

The second fix seems to indicate that there is a `\symdecl` for `halting-problem`, but I cannot find it.

**Comment by Jazzpirate** [comment]
When in doubt, choose the one you think shouldn't exist (so that it's referenced by definame), then right click the name and click "go to declaration" - that should open the file where the symbol comes from ;)

**Comment by kohlhase** [comment]
Thanks for the tip, this is really useful: There is a theorem over the same name that I did not "find".
